- summit/code/pages/SummitOverviewPage.php
Please see: https://bugs.launchpad.net/openstack-org/+bug/1488826
> Fixed Video Recap Typo with correct information

- speaker_bureau/code/ui/SpeakerContactForm.php
Attendance was spelled incorrectly
> Fix typo in speaker contact form

- summit/code/controllers/TrackChairAPI.php
- summit/code/infrastructure/active_records/events/presentations/Presentation.php
- summit/code/pages/EmailUtilsPage.php
- summit/javascript/new-trackchairs-app/app/comments-list.tag
- themes/openstack/css/presentation-editor.css
- themes/openstack/css/track-chair.css
- themes/openstack/templates/PresentationEditorPage.ss
- themes/openstack/templates/SpeakerManagerPage.ss
- themes/openstack/templates/TrackChairPage.ss
Noticed this in the speaker comments, but also this appears to stretch
in properties too. Also spelling correction chage to change in speaker
comments.
> spelling correction presentaion to presentation

- installation.md
Use of one too many backtick was causing issue in display on github changes in the install documentation.
Also add a note about PHP7
> Fix markdown syntax

- installation.md
> Fix Typo in installation.md

- themes/openstack/templates/Layout/InteropPage.ss
Update interop page to reference the latest required interoperability guidelines.
> Update latest guidelines

- auc-metrics/code/services/ActiveUserCommitteeWorkingGroupsService.php
> Fix typo in ActiveUserCommitteeWorkingGroupsService

- registration/templates/Layout/EditProfilePage_election.ss
Similar patch for 2015 -> 2016: https://github.com/OpenStackweb/openstack-org/commit/d883a5ebb0ea750865541647a548b1fb2f9e47a9
> Fixed link to 2017 elections candidate list

- summit/code/pages/SummitAppSchedPage.php
- summit/css/schedule-grid.css
- summit/templates/Layout/SummitAppSchedPage_globalSearchResults.ss
- summit/templates/Layout/SummitAppSpeakerPage.ss
- summit/ui/source/js/schedule/event-action-buttons.tag
- summit/ui/source/js/schedule/schedule-api.js
- summit/ui/source/js/schedule/schedule-event.tag
- summit/ui/source/js/schedule/schedule-grid-events.tag
* fixes on myfavorites view
* refactored components
* improveed load time
> [smarcet] - #12544

- auc-metrics/lib/uc-recognition/tools/get_active_wg_members.py
- auc-metrics/lib/uc-recognition/tools/get_meeting_data.sh
https://review.openstack.org/#/c/446384/ updated some AUC scripts,
sync with the upstream repo.
> Sync AUC scripts with upstream

- summit/_config/injector.yml
- summit/code/infrastructure/active_records/events/SummitEvent.php
- summit/code/models/managers/ScheduleManager.php
- summit/code/pages/SummitAppSchedPage.php
- summit/css/summitapp-event.css
- summit/templates/Layout/SummitAppEventPage.ss
- summit/ui/source/js/schedule/event-comments.tag
- summit/ui/source/js/schedule/event-detail.js
- summit/ui/source/js/schedule/feedback-form-comments.tag
- summit/ui/source/js/schedule/feedback-form-dispatcher.js
- summit/ui/source/js/schedule/feedback-form.tag
Added feedback form and reviews into event detail page
> [gluna] - #12191

- software/code/infrastructure/active_records/OpenStackApiVersion.php
- software/code/infrastructure/active_records/OpenStackComponent.php
- software/code/infrastructure/active_records/OpenStackRelease.php
- software/code/infrastructure/active_records/OpenStackReleaseSupportedApiVersion.php
- software/code/tasks/IngestOpenStackComponentsDataCronTask.php
- software/code/ui/admin/OpenStackApiVersionAdminUI.php
- software/code/ui/admin/OpenStackReleaseAdminUI.php
- software/code/ui/admin/OpenStackReleaseSupportedApiVersionAdminUI.php
- software/templates/Layout/SoftwareHomePage_getComponent.ss
* API Versions ingestion from http://git.openstack.org/cgit/openstack/project-navigator-data/tree/
> [smarcet] - #12809

- survey_builder/code/infrastructure/active_records/instances/SurveyAnswer.php
- survey_builder/code/infrastructure/active_records/instances/SurveyAnswerLog.php
- survey_builder/code/infrastructure/active_records/instances/SurveyRegularStep.php
- survey_builder/code/infrastructure/builders/SurveyBuilder.php
- survey_builder/code/model/SurveyManager.php
- survey_builder/code/model/instances/ISurveyRegularStep.php
* added table SurveyAnswerLog to store surver changes over time
> [smarcet] - #11554

- ICLA/code/cron_tasks/PullCLAFromGerritTask.php
- composer.json
- composer.lock
- cron_jobs_scheduler/_config.php
- cron_jobs_scheduler/_config/schedule.yml
- cron_jobs_scheduler/code/SchedulerCronTask.php
- cron_jobs_scheduler/readme.md
- gerrit_ingest/code/cron_tasks/PullCommitsFromGerritTask.php
- sengrid_webmailer/code/SendGridEmailSenderTask.php
* cron tab simplification
- added a new single entry point task SchedulerCronTask
where all cron jobs for site are ran using this configuration
cron_jobs_scheduler/_config/schedule.yml
> [smarcet] - #12977

- coa/_config/inyector.yml
- coa/code/infrastructure/active_records/CertifiedOpenStackAdministratorExam.php
- coa/code/infrastructure/repositories/SapphireCOAExamRepository.php
- coa/code/infrastructure/services/COAFileApi.php
- coa/code/interfaces/restfull_api/COACrudApi.php
- coa/code/model/ICertifiedOpenStackAdministratorExam.php
- coa/code/model/ICertifiedOpenStackAdministratorExamRepository.php
- coa/code/model/services/COAManager.php
- coa/code/model/services/ICOAManager.php
- coa/code/tasks/LoadInitialCOADump.php
* updated coa ingestion and created a new task to do initial ingestion
( deletes all former instances)
> [smarcet] - #12962

- gettext/Locale/zh_CN/LC_MESSAGES/survey_template.po
@smarcet : Plz review and merge - thanks a lot in advance!
> [User Survey] Updates zh_CN translation

- gettext/Locale/jp_JP/LC_MESSAGES/survey_template.po
- gettext/Locale/jp_JP/LC_MESSAGES/survey_ui.po
BTW, jp_JP is the correct local name? ja_JP (or ja) is usual.
> [User Survey] Updates Japanese translation

- registration/code/infrastructure/active_records/MemberEmailChange.php
- registration/code/infrastructure/active_records/MemberPasswordChange.php
- registration/code/infrastructure/active_records/OpenStackMember.php
* added tracking log for member email / password changes
> [smarcet] - #13034

- migrations/migrations.yml
- openstack/code/utils/DB/Order.php
- openstack/code/utils/DB/OrderElement.php
- openstack/code/utils/DB/OrderParser.php
- openstack/code/utils/DB/PagingInfo.php
- survey_builder/code/infrastructure/repositories/SapphireSurveyRepository.php
- survey_builder/code/migrations/UpgradeSurveyLangMigration.php
- survey_builder/code/model/instances/ISurveyRepository.php
- survey_builder/code/ui/admin/sangria/SangriaSurveyBuilderExtension.php
- survey_builder/js/survey.sangria.surveys.list.filter.js
- survey_builder/templates/Layout/Includes/SangriaPage_SurveyBuilderListFilter.ss
- survey_builder/templates/Layout/SangriaPage_SurveyBuilderListDeployments.ss
- survey_builder/templates/Layout/SangriaPage_SurveyBuilderListSurveys.ss
- themes/openstack/javascript/querystring.jquery.js
* added Ability to multi-select values if there is a dropdown of answer choices
* added Export results
* fixed issue with counts
* added option to select # per page and/or All at bottom
> [smarcet] - #13174

- auc-metrics/_config/config.yml
As discussed with @jimmytipit , he may be taking this over. If confirmed, merge :)
> Change AUC Metrics email to jimmy

- migrations/migrations.yml
- survey_builder/code/infrastructure/active_records/templates/questions/SurveyCheckBoxListQuestionTemplate.php
- survey_builder/code/infrastructure/active_records/templates/questions/SurveyDoubleEntryTableQuestionTemplate.php
- survey_builder/code/infrastructure/active_records/templates/questions/SurveyMultiValueQuestionTemplate.php
- survey_builder/code/infrastructure/active_records/templates/questions/SurveyQuestionValueTemplate.php
- survey_builder/code/infrastructure/active_records/templates/questions/SurveyQuestionValueTemplateGroup.php
- survey_builder/code/infrastructure/active_records/templates/questions/SurveyRadioButtonListQuestionTemplate.php
- survey_builder/code/migrations/UpdatedSurveyQuestionsMigration.php
- survey_builder/code/ui/frontend/SurveyPage.php
- survey_builder/code/ui/frontend/builders/fields/SurveyRadioButtonListQuestionTemplateUIBuilder.php
- survey_builder/code/ui/frontend/forms/fields/SurveyRadioButtonMatrixField.php
- survey_builder/code/ui/frontend/forms/fields/SurveyRadioButtonSetField.php
- survey_builder/css/SurveyRadioButtonSetField.css
- survey_builder/css/survey.radio.button.matrix.field.css
- survey_builder/templates/SurveyRadioButtonMatrixField.ss
- survey_builder/templates/SurveyRadioButtonSetField.ss
* allow to set group of values per multivalue question
* added orientation field to radio button list
> [smarcet] - #13970

- themes/openstack/templates/Layout/Includes/Navigation_Footer.ss
> Update Projects link

- openstack/code/landing-pages/AboutMascots.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2821328&fileview=grid
Signed-off-by: romanetar roman_ag@hotmail.com
> filter empty bucket images

- openstack/_config/injector.yml
- openstack/code/extensions/CustomAssetAdmin.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&fileview=grid
Signed-off-by: romanetar [roman_ag@hotmail.com](mailto:roman_ag@hotmail.com)
> remove Sync Files button

- marketplace/code/infrastructure/queries/TrainingCoursesCompanyQueryHandler.php
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2935930&fileview=grid
Signed-off-by: romanetar <roman_ag@hotmail.com>
> relax training courses company query to list companies without TrainingCourseSchedule in the filter combo box

- marketplace/templates/Layout/ConsultantsDirectoryPage.ss
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2889908&fileview=grid
Signed-off-by: romanetar <roman_ag@hotmail.com>
> change "Filter Consultants" description to "Filter Providers"

- openstack/code/CompanyListPage.php
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2533305&fileview=grid
> adding relational table and company name sorting

- marketplace/templates/Layout/CloudsDirectoryPage_cloud.ss
- marketplace/templates/Layout/DistributionsDirectoryPage_implementation.ss
- marketplace/templates/Layout/Includes/CloudsDirectoryPage_CloudBox.ss
- marketplace/templates/Layout/Includes/DistributionsDirectoryPage_ImplementationBox.ss
- marketplace/templates/Layout/Includes/MarketPlaceCompany.ss
- marketplace/templates/Layout/Includes/RemoteCloudsDirectoryPage_ImplementationBox.ss
- marketplace/templates/Layout/RemoteCloudsDirectoryPage_implementation.ss
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3550155&stafilter=NotComplete&fileview=grid
Signed-off-by: romanetar [roman_ag@hotmail.com]
> feat: marketplace content tweaks

- themes/openstack/scss/vmwaremigration.scss
- themes/openstack/templates/Layout/VMWareMigration.ss
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3751402&stafilter=NotComplete&fileview=grid
> fix: logos replacement and css tweak

- user-stories/js/user.story.form.js
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3784716&stafilter=NotComplete&fileview=grid
> Bugfix - change autocomplete min char limit

- papers/scss/paper-viewer-page.scss
ref https://tipit.avaza.com/project/view/188885#!tab=task-pane&task=3807635
> fix: Ensure consistent font sizing across lists and nested lists
