themes/openstack/templates/Layout/InteropPage.ss

Updated the interop page to clarify which releases are tested
against, and to add that RefStack Client is the only approved
method of submitting test results to the Foundation.

Updated Interop page with current information.

---

themes/openstack/templates/Layout/InteropPage.ss

Updated the Interop page to add new information about the
"Compatible" logo licensing changes. New logos for Storage
drivers now require that the drivers pass the third-party
CI testing for Cinder.

Updated Interop page to add "Compatible" driver information

---

themes/openstack/templates/Layout/InteropPage.ss

After reviewing the recently deployed Interop page, a
number of broken, moved, and out-of-date links were
uncovered. This patch corrects and updates the links
and makes minor language clarifications.

Fixed broken, moved, and outdated links.

---

summit/code/pages/SummitOverviewPage.php

Hello,
Although I modified the source as https://github.com/OpenStackweb/openstack-org/pull/3 , I have found that the production page did not show correct information. I am not sure whether this change would be merged well with your update logistics or not, but please just consider that this change should be reflected to production homepage. 
And also, please change the bug status on launchpad: https://bugs.launchpad.net/openstack-org/+bug/1488826
With many thanks,

Fixed Video Recap Typo on production branch

---

themes/openstack/templates/Layout/Includes/HomePageBottom.ss

developer.openstack.org runs only on http. When www.openstack.org is
visited over https, the link to developer.openstack.org is pointed over
https. This throws an error. Chaning it to default to http.

Default developer.openstack.org link to http

---

events/templates/Layout/EventHolder.ss

Current banner in http://www.openstack.org/community/events/
is already updated for Austin Summit, but the link is still Tokyo Summit.

Summit banner link fixed for Austin Summit

---

themes/openstack/templates/Layout/Includes/Footer.ss

I have found inconsistency between www.openstack.org and groups.openstack.org,
After seeing https://review.openstack.org/#/c/139421/ , I think new link in www.o.o is better than previous one.
Moreover, it can address one bug: https://bugs.launchpad.net/openstack-org/+bug/1528978 .

Changes "Contribute" link on the bottom

---

themes/openstack/templates/Layout/InteropPage.ss

Updates the current active guidelines on the OpenStack DefCore/Interoperability page.

Update current guidelines on interop page

---

surveys/templates/email/DeploymentSurveyEmail.ss

The Groups Portal has replaced the wiki page, so this URL needs to be updated.

Update user groups URL in survey thank you message

---

migrations/migrations.yml
summit/code/infrastructure/active_records/events/presentations/Presentation.php
summit/code/migrations/VideoPresentationMigration.php

This migration script is designed to deprecate the old `VideoPresentation` table in favour of the new `PresentationMaterial` object and its descendant `PresentationVideo`.
With the build of the new Summit video page, it became clear that there are some serious integrity issues with the relation between Summit, Presentation, and Videos, particularly in older Summits. In order to create a user experience that will deliver videos across all summits, it is necessary to eliminate idiosyncrasies and establish a consistent data model that we can use long term.
First, the script ensures that old summits that predate the `Summit` object (San Diego, Portland, Atlanta) are stored in the database as hollow shells, with the bare minimum fields populated, with minimal real-life accuracy.  The purpose …

Migration script to deprecate VideoPresentation table

---

themes/openstack/templates/Layout/InteropPage.ss

Clarified that the two latest DefCore guidelines cover four
OpenStack releases.

Updated interop page to clarify convered releases.

---

themes/openstack/templates/Layout/InteropPage.ss

DefCore no longer maintains the generated required and
flagged lists. This information has been updated to point
to the RefStack server.
Block storage testing is now required, so removing future
tense from testing section.

Updated Interop page with latest testing information

---

events/code/ui/EventHolder.php
events/code/ui/admin/SangriaPageEventExtension.php
events/css/openstackhackathons.css
events/templates/Layout/EventHolder_openstackhackathons.ss
sangria/templates/Layout/SangriaPage.ss
summit-voting-app/templates/PresentationVotingPage.ss
themes/openstack/templates/Layout/Includes/Navigation_menu.ss

App Hackathons are becoming increasingly prevalent and there is no
current home for them on OpenStack.org. This change uses the same
style as OpenStack Days, to provide a way for App Hackathons to be
listed.

Add EventHolder for App Hackathons

---

summit/code/infrastructure/active_records/events/presentations/PresentationSpeaker.php

Also account for failures to find appropriate word breaks.
Previously, getShortBio would return just `'...'` if there were no spaces after the `$length`th character. You could see this, for example, at https://www.openstack.org/summit/barcelona-2016/summit-schedule/events/15968/new-in-swift-object-encryption

Make length arg of getShortBio a hard limit

---

auc-metrics/code/services/OfficialUserGroupOrganizerService.php

The URL previously used included all user group organisers.
The change limits it to just official user groups, as per AUC spec.

Fix AUC Metric OFFICIAL_USER_GROUP_ORGANIZER

---

software/templates/Layout/SoftwareHomePage_getComponent.ss

At the Austin Summit, working with package maintainers, the ops
tags team decided on a way to markedly improve the ops:packaged tag:
https://etherpad.openstack.org/p/AUS-ops-Ops-tags
Unfortunately, these changes have not been implemented and the tag
has not been updated as a result.
Until these changes have been implemented, the ops:package tag should
not be displayed on the project navigator.

Stop displaying ops:packaged

---

themes/openstack/templates/Layout/CommunityPageBis.ss

Also write out the names of the various mailing lists instead of using
acronyms.

Add sig mailing list to contributor portal

---

migrations/migrations.yml
openstack/code/CommunityPageBis.php
software/_config.php
software/code/infrastructure/active_records/OpenStackComponent.php
software/code/infrastructure/active_records/OpenStackComponentCategory.php
software/code/infrastructure/active_records/OpenStackComponentSubCategory.php
software/code/infrastructure/active_records/OpenStackComponentTag.php
software/code/infrastructure/active_records/OpenStackRelease.php
software/code/infrastructure/active_records/OpenStackReleaseSupportedApiVersion.php
software/code/migrations/PopulateComponentCategoriesMigration.php
software/code/migrations/PopulateSubCategoriesAndTagsMigration.php
software/code/model/IOpenStackComponent.php
software/code/model/IOpenStackComponentCategory.php
software/code/model/IOpenStackComponentSubCategory.php
software/code/model/IOpenStackComponentTag.php
software/code/model/SoftwareManager.php
software/code/tasks/IngestOpenStackComponentsDataCronTask.php
software/code/ui/SoftwareHomePage.php
software/code/ui/admin/OpenStackComponentAdminUI.php
software/code/ui/admin/OpenStackComponentCategoryAdminUI.php
software/code/ui/admin/OpenStackComponentSubCategoryAdminUI.php
software/code/ui/admin/OpenStackComponentTagAdminUI.php
software/code/ui/admin/SoftwareModelAdmin.php
software/templates/Layout/SoftwareHomePage_getComponent.ss

component category cms
WIP
migration and tags
bug fix migration
bugfix
rollback injest task and fix cms grids
changes on admin

[spalenque] - #13550 * Project Navigator Revamp

---

themes/openstack/css/community-bis.css
themes/openstack/templates/Layout/CommunityPageBis.ss

Fixes for the "How to communicate" and "Quick links" sections of the page to point to more relevant content (and fix dead links).

Contributor portal fixes

---

themes/openstack/templates/Layout/AppDevHomePage.ss

The link is dead because this guide does not exist anymore. For now,
point to the SDK getting started guide. We'll see what we can do about
reworking for the firstapp stuff.

Update link to firstapp guide

---

Dockerfile
PythonEnv.md
docker.md
gettext/readme.md
init_site.sh
scripts/bootstrap.sh

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Signed-off-by: Pratik raj <rajpratik71@gmail.com>

Some debian package manager tweaks

---

themes/openstack/templates/Layout/BareMetalPage.ss

The link to metal3 doesn't work anymore and likely want to link to your project instead of a different one.

Update link to Ironic Docs

---

elections/code/infrastructure/active_records/Candidate.php
elections/code/infrastructure/active_records/Election.php

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3685586&stafilter=NotComplete&fileview=grid

add candidate bio prop and editor in admin

---

summit/code/infrastructure/active_records/Summit.php

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=3809130&stafilter=NotComplete&fileview=grid

fix: Column 'Level' in where clause is ambiguous

---

members_list/code/ui/frontend/MemberListPage.php

This query returns a record with "id":162837 https://openstackid-resources.openstack.org/api/public/v1/members?expand=groups%2Call_affiliations%2Call_affiliations.organization&filter%5B%5D=email%3D%3Dlazekteam%40gmail.com&filter%5B%5D=membership_type%3D%3DIndividual&relations=affiliations%2Cgroups
but https://www.openstack.org/community/members/profile/162837 returns a 404 page
Change member filtering from GroupID 5 to MembershipType "Individual".
-  In `MemberList` method of `members_list/code/ui/frontend/MemberListPage.php` from `GroupID = 5` to `MembershipType = IOpenStackMember::MembershipTypeIndividual`
- In `findMember` from `inGroup(5, true)` to `MembershipType === IOpenStackMember::MembershipTypeIndividual`
- https://tipit.avaza.com/task#task=3848895
This PR is related with this …

[Task 3848895] Member Data Lookup Issue
